### PR TITLE
Support options in vrp and pdp

### PR DESCRIPTION
**Pull request by asoesilo**
Allows users to specify the options to set in both VRP and PDP.

### CODE REVIEW

**Comment by asoesilo** [comment]
@mck- @acroca ready for review

**Comment by acroca** [comment]
Looks good to me

**Comment by mck-** [comment]
Maybe update README as well?

**Comment by asoesilo** [comment]
@mck- ready for review

**Comment by mck-** [comment]
Sorry, actually I think `setOption` makes more sense than `addOption` – other than that, 🚢

**Pull request merged**
